version: "2" # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 100

engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
  brakeman:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
  markdownlint:
    enabled: true
  git-legal:
    enabled: true

exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*.d.ts"
